// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: pkg/grpc/proto/tenant_service.proto

package tenantservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tenant represents tenant information
type Tenant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_pkg_grpc_proto_tenant_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_tenant_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_tenant_service_proto_rawDescGZIP(), []int{0}
}

func (x *Tenant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tenant) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Tenant) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tenant) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Tenant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Tenant) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// GetTenantRequest contains the tenant ID to retrieve
type GetTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantRequest) Reset() {
	*x = GetTenantRequest{}
	mi := &file_pkg_grpc_proto_tenant_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantRequest) ProtoMessage() {}

func (x *GetTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_tenant_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantRequest.ProtoReflect.Descriptor instead.
func (*GetTenantRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_tenant_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// GetTenantResponse contains the tenant data or error information
type GetTenantResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetTenantResponse_Tenant
	//	*GetTenantResponse_Error
	Result        isGetTenantResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantResponse) Reset() {
	*x = GetTenantResponse{}
	mi := &file_pkg_grpc_proto_tenant_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantResponse) ProtoMessage() {}

func (x *GetTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_tenant_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantResponse.ProtoReflect.Descriptor instead.
func (*GetTenantResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_tenant_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTenantResponse) GetResult() isGetTenantResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetTenantResponse) GetTenant() *Tenant {
	if x != nil {
		if x, ok := x.Result.(*GetTenantResponse_Tenant); ok {
			return x.Tenant
		}
	}
	return nil
}

func (x *GetTenantResponse) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*GetTenantResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isGetTenantResponse_Result interface {
	isGetTenantResponse_Result()
}

type GetTenantResponse_Tenant struct {
	Tenant *Tenant `protobuf:"bytes,1,opt,name=tenant,proto3,oneof"`
}

type GetTenantResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetTenantResponse_Tenant) isGetTenantResponse_Result() {}

func (*GetTenantResponse_Error) isGetTenantResponse_Result() {}

// GetTenantsRequest contains multiple tenant IDs to retrieve
type GetTenantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantIds     []string               `protobuf:"bytes,1,rep,name=tenant_ids,json=tenantIds,proto3" json:"tenant_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantsRequest) Reset() {
	*x = GetTenantsRequest{}
	mi := &file_pkg_grpc_proto_tenant_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantsRequest) ProtoMessage() {}

func (x *GetTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_tenant_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantsRequest.ProtoReflect.Descriptor instead.
func (*GetTenantsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_tenant_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTenantsRequest) GetTenantIds() []string {
	if x != nil {
		return x.TenantIds
	}
	return nil
}

// GetTenantsResponse contains the list of tenants or error information
type GetTenantsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Tenants          []*Tenant              `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	Error            string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                                                 // Global error if request fails completely
	MissingTenantIds []string               `protobuf:"bytes,3,rep,name=missing_tenant_ids,json=missingTenantIds,proto3" json:"missing_tenant_ids,omitempty"` // IDs that were not found
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetTenantsResponse) Reset() {
	*x = GetTenantsResponse{}
	mi := &file_pkg_grpc_proto_tenant_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantsResponse) ProtoMessage() {}

func (x *GetTenantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_tenant_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantsResponse.ProtoReflect.Descriptor instead.
func (*GetTenantsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_tenant_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetTenantsResponse) GetTenants() []*Tenant {
	if x != nil {
		return x.Tenants
	}
	return nil
}

func (x *GetTenantsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetTenantsResponse) GetMissingTenantIds() []string {
	if x != nil {
		return x.MissingTenantIds
	}
	return nil
}

// GetTenantBySlugRequest contains the tenant slug to retrieve
type GetTenantBySlugRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantBySlugRequest) Reset() {
	*x = GetTenantBySlugRequest{}
	mi := &file_pkg_grpc_proto_tenant_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantBySlugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantBySlugRequest) ProtoMessage() {}

func (x *GetTenantBySlugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_tenant_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantBySlugRequest.ProtoReflect.Descriptor instead.
func (*GetTenantBySlugRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_tenant_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetTenantBySlugRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

var File_pkg_grpc_proto_tenant_service_proto protoreflect.FileDescriptor

const file_pkg_grpc_proto_tenant_service_proto_rawDesc = "" +
	"\n" +
	"#pkg/grpc/proto/tenant_service.proto\x12\rtenantservice\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf0\x01\n" +
	"\x06Tenant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"/\n" +
	"\x10GetTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"f\n" +
	"\x11GetTenantResponse\x12/\n" +
	"\x06tenant\x18\x01 \x01(\v2\x15.tenantservice.TenantH\x00R\x06tenant\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\b\n" +
	"\x06result\"2\n" +
	"\x11GetTenantsRequest\x12\x1d\n" +
	"\n" +
	"tenant_ids\x18\x01 \x03(\tR\ttenantIds\"\x89\x01\n" +
	"\x12GetTenantsResponse\x12/\n" +
	"\atenants\x18\x01 \x03(\v2\x15.tenantservice.TenantR\atenants\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12,\n" +
	"\x12missing_tenant_ids\x18\x03 \x03(\tR\x10missingTenantIds\",\n" +
	"\x16GetTenantBySlugRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug2\x8e\x02\n" +
	"\rTenantService\x12N\n" +
	"\tGetTenant\x12\x1f.tenantservice.GetTenantRequest\x1a .tenantservice.GetTenantResponse\x12Q\n" +
	"\n" +
	"GetTenants\x12 .tenantservice.GetTenantsRequest\x1a!.tenantservice.GetTenantsResponse\x12Z\n" +
	"\x0fGetTenantBySlug\x12%.tenantservice.GetTenantBySlugRequest\x1a .tenantservice.GetTenantResponseB)Z'wibusystem/pkg/grpc/proto/tenantserviceb\x06proto3"

var (
	file_pkg_grpc_proto_tenant_service_proto_rawDescOnce sync.Once
	file_pkg_grpc_proto_tenant_service_proto_rawDescData []byte
)

func file_pkg_grpc_proto_tenant_service_proto_rawDescGZIP() []byte {
	file_pkg_grpc_proto_tenant_service_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_proto_tenant_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_proto_tenant_service_proto_rawDesc), len(file_pkg_grpc_proto_tenant_service_proto_rawDesc)))
	})
	return file_pkg_grpc_proto_tenant_service_proto_rawDescData
}

var file_pkg_grpc_proto_tenant_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_grpc_proto_tenant_service_proto_goTypes = []any{
	(*Tenant)(nil),                 // 0: tenantservice.Tenant
	(*GetTenantRequest)(nil),       // 1: tenantservice.GetTenantRequest
	(*GetTenantResponse)(nil),      // 2: tenantservice.GetTenantResponse
	(*GetTenantsRequest)(nil),      // 3: tenantservice.GetTenantsRequest
	(*GetTenantsResponse)(nil),     // 4: tenantservice.GetTenantsResponse
	(*GetTenantBySlugRequest)(nil), // 5: tenantservice.GetTenantBySlugRequest
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
}
var file_pkg_grpc_proto_tenant_service_proto_depIdxs = []int32{
	6, // 0: tenantservice.Tenant.created_at:type_name -> google.protobuf.Timestamp
	6, // 1: tenantservice.Tenant.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: tenantservice.GetTenantResponse.tenant:type_name -> tenantservice.Tenant
	0, // 3: tenantservice.GetTenantsResponse.tenants:type_name -> tenantservice.Tenant
	1, // 4: tenantservice.TenantService.GetTenant:input_type -> tenantservice.GetTenantRequest
	3, // 5: tenantservice.TenantService.GetTenants:input_type -> tenantservice.GetTenantsRequest
	5, // 6: tenantservice.TenantService.GetTenantBySlug:input_type -> tenantservice.GetTenantBySlugRequest
	2, // 7: tenantservice.TenantService.GetTenant:output_type -> tenantservice.GetTenantResponse
	4, // 8: tenantservice.TenantService.GetTenants:output_type -> tenantservice.GetTenantsResponse
	2, // 9: tenantservice.TenantService.GetTenantBySlug:output_type -> tenantservice.GetTenantResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_grpc_proto_tenant_service_proto_init() }
func file_pkg_grpc_proto_tenant_service_proto_init() {
	if File_pkg_grpc_proto_tenant_service_proto != nil {
		return
	}
	file_pkg_grpc_proto_tenant_service_proto_msgTypes[2].OneofWrappers = []any{
		(*GetTenantResponse_Tenant)(nil),
		(*GetTenantResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_proto_tenant_service_proto_rawDesc), len(file_pkg_grpc_proto_tenant_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_proto_tenant_service_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_proto_tenant_service_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_proto_tenant_service_proto_msgTypes,
	}.Build()
	File_pkg_grpc_proto_tenant_service_proto = out.File
	file_pkg_grpc_proto_tenant_service_proto_goTypes = nil
	file_pkg_grpc_proto_tenant_service_proto_depIdxs = nil
}
