services:
  system_dev:
    image: postgres:18.0
    container_name: system_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: system_dev
      POSTGRES_USER: system_dev
      POSTGRES_PASSWORD: system_dev
    ports:
      - "5432:5432"
    volumes:
      - system_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U system_dev -d system_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wibusystem_backend

  # Redis for caching and message queue
  redis:
    image: redis:8.2.1-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass 8767375c91873d04626c73c8aed8ce01
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wibusystem_backend

  grafana:
    image: grafana/grafana:12.3.0-19020365962
    container_name: grafana
    restart: unless-stopped
    ports:
      - "5555:3000" # Truy cập Grafana tại http://localhost:5555
    volumes:
      - grafana_data:/var/lib/grafana
      # Tự động thêm Loki làm Nguồn dữ liệu
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/loki-datasource.yml
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin # Đổi password này nếu muốn
    networks:
      - wibusystem_backend
  loki:
    image: grafana/loki:3.5
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100" # Port nội bộ cho Promtail và Grafana
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - loki_data:/loki
      - ./loki-config.yml:/etc/loki/loki-config.yml
    networks:
      - wibusystem_backend

  promtail:
    image: grafana/promtail:3.5
    container_name: promtail
    restart: unless-stopped
    ports:
      - "9080:9080" # Expose Promtail metrics and API
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Cho phép Promtail đọc log từ Docker
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
    networks:
      - wibusystem_backend

volumes:
  system_data:
    driver: local
  redis_data:
    driver: local
  grafana_data:
    driver: local
  loki_data:
    driver: local

networks:
  wibusystem_backend:
    driver: bridge
    name: wibusystem-backend
