// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"database/sql"
	"fmt"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/ory/fosite"
	"github.com/redis/go-redis/v9"
	"go.uber.org/zap"
	"net/http"
	"system/configs"
	"system/internal/app/router"
	"system/internal/ent/generated"
	"system/internal/modules/analytics"
	"system/internal/modules/artist"
	"system/internal/modules/auth"
	"system/internal/modules/author"
	"system/internal/modules/creator"
	"system/internal/modules/email"
	"system/internal/modules/embedding"
	"system/internal/modules/genre"
	"system/internal/modules/media"
	"system/internal/modules/media_progress"
	"system/internal/modules/novel"
	"system/internal/modules/novel_chapter"
	"system/internal/modules/novel_volume"
	"system/internal/modules/oauth2"
	"system/internal/modules/organization"
	"system/internal/modules/payment"
	"system/internal/modules/user"
	"system/internal/platform/cache"
	"system/internal/platform/database"
	"system/internal/platform/i18n"
	oauth2_2 "system/internal/platform/oauth2"
	"system/internal/platform/oauth2/storage"
	"system/internal/platform/resend"
	"system/internal/platform/socket"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

// InitializeApplication wires all dependencies
func InitializeApplication(ctx context.Context, cfg *configs.Config, logger *zap.Logger, i18nInstance *i18n.I18n, rdb *database.RedisClient, ch *database.ClickHouseClient) (*Application, error) {
	oAuthConfig := ProvideOAuthConfig(cfg)
	client, err := ProvideEntClient(ctx, cfg, logger)
	if err != nil {
		return nil, err
	}
	db, err := ProvideDBFromEnt(cfg)
	if err != nil {
		return nil, err
	}
	oAuth2ClientRepository := oauth2.NewOAuth2ClientEntRepository(client, db)
	oAuth2SessionRepository := oauth2.NewOAuth2SessionEntRepository(client)
	sqlStore := storage.NewSQLStore(oAuth2ClientRepository, oAuth2SessionRepository)
	redisStore := storage.NewRedisStore(rdb, oAuth2ClientRepository, logger)
	hybridStore := storage.NewHybridStore(sqlStore, redisStore)
	oAuth2Provider := oauth2_2.NewOAuth2Provider(hybridStore, oAuthConfig)
	userRepository := user.NewUserEntRepository(client, db)
	sessionRepository := user.NewSessionRepository(rdb)
	userService := user.NewService(userRepository, sessionRepository)
	authRequestRepository := oauth2.NewAuthRequestRepository(rdb, oAuth2ClientRepository)
	consentRepository := oauth2.NewConsentEntRepository(client)
	oAuth2Service := oauth2.NewService(userService, authRequestRepository, consentRepository, oAuth2SessionRepository, oAuth2ClientRepository)
	webAuthnConfig := ProvideWebAuthnConfig(cfg)
	webAuthnCredentialRepository := auth.NewWebAuthnCredentialEntRepository(client)
	webAuthnSessionRepository := auth.NewWebAuthnSessionEntRepository(client)
	webAuthnService, err := auth.NewWebAuthnService(webAuthnConfig, webAuthnCredentialRepository, webAuthnSessionRepository, userRepository, logger)
	if err != nil {
		return nil, err
	}
	handler := oauth2.NewHandler(oAuthConfig, oAuth2Provider, oAuth2Service, authRequestRepository, oAuth2ClientRepository, webAuthnService, logger)
	oAuth2AdminService := oauth2.NewAdminService(oAuth2ClientRepository)
	adminHandler := oauth2.NewAdminHandler(oAuth2AdminService)
	emailVerificationRepository := auth.NewEmailVerificationEntRepository(client, db)
	passwordResetRepository := auth.NewPasswordResetEntRepository(client, db)
	roleRepository := user.NewRoleEntRepository(client)
	authService := auth.NewService(userService, emailVerificationRepository, passwordResetRepository, roleRepository)
	emailConfig := ProvideEmailConfig(cfg)
	resendClient := resend.NewClient(emailConfig, logger)
	service := email.NewService(resendClient, emailConfig)
	registerUserUseCase := auth.NewRegisterUserUseCase(authService)
	verifyEmailUseCase := auth.NewVerifyEmailUseCase(authService)
	forgotPasswordUseCase := auth.NewForgotPasswordUseCase(authService)
	resetPasswordUseCase := auth.NewResetPasswordUseCase(authService)
	authHandler := auth.NewHandler(authService, service, webAuthnService, oAuth2Service, registerUserUseCase, verifyEmailUseCase, forgotPasswordUseCase, resetPasswordUseCase)
	genreRepository := genre.NewEntGenreRepository(client)
	genreService := genre.NewService(genreRepository)
	createGenreUseCase := genre.NewCreateGenreUseCase(genreService)
	updateGenreUseCase := genre.NewUpdateGenreUseCase(genreService)
	deleteGenreUseCase := genre.NewDeleteGenreUseCase(genreService)
	getGenreUseCase := genre.NewGetGenreUseCase(genreService)
	listGenresUseCase := genre.NewListGenresUseCase(genreService)
	listSelectionUseCase := genre.NewListSelectionUseCase(genreService)
	mergeGenresUseCase := genre.NewMergeGenresUseCase(genreService)
	previewMergeUseCase := genre.NewPreviewMergeUseCase(genreService)
	viewAnalyticsRepository := analytics.NewViewAnalyticsClickHouseRepository(ch)
	novelRepository := novel.NewEntNovelRepository(client)
	novelVolumeRepository := novel_volume.NewEntVolumeRepository(client)
	authorRepository := author.NewEntAuthorRepository(client)
	artistRepository := artist.NewEntArtistRepository(client)
	creatorRepository := creator.NewEntRepository(client, db)
	novelService := novel.NewService(novelRepository, novelVolumeRepository, genreRepository, authorRepository, artistRepository, creatorRepository)
	organizationRepository := organization.NewEntRepository(client, db)
	novelChapterRepository := novel_chapter.NewEntChapterRepository(client)
	analyticsService := analytics.NewService(viewAnalyticsRepository, novelService, creatorRepository, organizationRepository, novelChapterRepository, userRepository, genreRepository, rdb, logger)
	genreHandler := genre.NewHandler(createGenreUseCase, updateGenreUseCase, deleteGenreUseCase, getGenreUseCase, listGenresUseCase, listSelectionUseCase, mergeGenresUseCase, previewMergeUseCase, analyticsService, logger)
	authorService := author.NewService(authorRepository)
	createAuthorUseCase := author.NewCreateAuthorUseCase(authorService)
	updateAuthorUseCase := author.NewUpdateAuthorUseCase(authorService)
	deleteAuthorUseCase := author.NewDeleteAuthorUseCase(authorService)
	getAuthorUseCase := author.NewGetAuthorUseCase(authorService)
	listAuthorsUseCase := author.NewListAuthorsUseCase(authorService)
	authorListSelectionUseCase := author.NewListSelectionUseCase(authorService)
	mergeAuthorsUseCase := author.NewMergeAuthorsUseCase(authorService)
	authorPreviewMergeUseCase := author.NewPreviewMergeUseCase(authorService)
	authorHandler := author.NewHandler(createAuthorUseCase, updateAuthorUseCase, deleteAuthorUseCase, getAuthorUseCase, listAuthorsUseCase, authorListSelectionUseCase, mergeAuthorsUseCase, authorPreviewMergeUseCase, logger)
	artistService := artist.NewService(artistRepository)
	createArtistUseCase := artist.NewCreateArtistUseCase(artistService)
	updateArtistUseCase := artist.NewUpdateArtistUseCase(artistService)
	deleteArtistUseCase := artist.NewDeleteArtistUseCase(artistService)
	getArtistUseCase := artist.NewGetArtistUseCase(artistService)
	listArtistsUseCase := artist.NewListArtistsUseCase(artistService)
	artistListSelectionUseCase := artist.NewListSelectionUseCase(artistService)
	mergeArtistsUseCase := artist.NewMergeArtistsUseCase(artistService)
	artistPreviewMergeUseCase := artist.NewPreviewMergeUseCase(artistService)
	artistHandler := artist.NewHandler(createArtistUseCase, updateArtistUseCase, deleteArtistUseCase, getArtistUseCase, listArtistsUseCase, artistListSelectionUseCase, mergeArtistsUseCase, artistPreviewMergeUseCase, logger)
	transactionManager := ProvideTransactionManager(client)
	creatorService := creator.NewService(creatorRepository, analyticsService, novelService, logger)
	repository := embedding.NewEntRepository(client, db)
	embeddingConfig := ProvideEmbeddingConfig(cfg)
	embedder := ProvideNoopEmbedder(embeddingConfig)
	redisClient := ProvideRedisGoClient(rdb)
	embeddingService := embedding.NewService(repository, embedder, redisClient, logger, embeddingConfig)
	createNovelUseCase := novel.NewCreateNovelUseCase(transactionManager, novelService, genreService, authorService, artistService, creatorService, embeddingService)
	updateNovelUseCase := novel.NewUpdateNovelUseCase(novelService, embeddingService)
	deleteNovelUseCase := novel.NewDeleteNovelUseCase(transactionManager, novelService, genreService, creatorService)
	getNovelUseCase := novel.NewGetNovelUseCase(novelService)
	listNovelsUseCase := novel.NewListNovelsUseCase(novelService)
	incrementViewCountUseCase := novel.NewIncrementViewCountUseCase(novelService)
	getNovelFullUseCase := novel.NewGetNovelFullUseCase(novelService)
	volumeHistoryRepository := novel_volume.NewVolumeHistoryEntRepository(client)
	volumeService := novel_volume.NewService(novelVolumeRepository, novelRepository, volumeHistoryRepository)
	chapterHistoryRepository := novel_chapter.NewChapterHistoryEntRepository(client)
	viewTrackingRepository := analytics.NewViewTrackingRedisRepository(rdb)
	chapterService := novel_chapter.NewService(novelChapterRepository, novelVolumeRepository, novelRepository, chapterHistoryRepository, creatorRepository, viewTrackingRepository, userRepository)
	topNovelAdapter := router.NewTopNovelAdapter(analyticsService)
	novelHandler := novel.NewHandler(novelService, createNovelUseCase, updateNovelUseCase, deleteNovelUseCase, getNovelUseCase, listNovelsUseCase, incrementViewCountUseCase, getNovelFullUseCase, volumeService, chapterService, topNovelAdapter)
	createVolumeUseCase := novel_volume.NewCreateVolumeUseCase(volumeService)
	updateVolumeUseCase := novel_volume.NewUpdateVolumeUseCase(volumeService)
	deleteVolumeUseCase := novel_volume.NewDeleteVolumeUseCase(volumeService)
	getVolumeUseCase := novel_volume.NewGetVolumeUseCase(volumeService)
	listVolumesByNovelUseCase := novel_volume.NewListVolumesByNovelUseCase(volumeService)
	updateDisplayOrderUseCase := novel_volume.NewUpdateDisplayOrderUseCase(volumeService)
	publishVolumeUseCase := novel_volume.NewPublishVolumeUseCase(volumeService)
	unpublishVolumeUseCase := novel_volume.NewUnpublishVolumeUseCase(volumeService)
	novel_volumeHandler := novel_volume.NewHandler(volumeService, createVolumeUseCase, updateVolumeUseCase, deleteVolumeUseCase, getVolumeUseCase, listVolumesByNovelUseCase, updateDisplayOrderUseCase, publishVolumeUseCase, unpublishVolumeUseCase)
	createChapterUseCase := novel_chapter.NewCreateChapterUseCase(chapterService)
	updateChapterUseCase := novel_chapter.NewUpdateChapterUseCase(chapterService)
	deleteChapterUseCase := novel_chapter.NewDeleteChapterUseCase(chapterService)
	getChapterUseCase := novel_chapter.NewGetChapterUseCase(chapterService)
	listChaptersByNovelUseCase := novel_chapter.NewListChaptersByNovelUseCase(chapterService)
	listChaptersByVolumeUseCase := novel_chapter.NewListChaptersByVolumeUseCase(chapterService)
	publishChapterUseCase := novel_chapter.NewPublishChapterUseCase(chapterService)
	scheduleChapterUseCase := novel_chapter.NewScheduleChapterUseCase(chapterService)
	viewTrackingConfig := ProvideViewTrackingConfig(cfg)
	viewTrackingService := analytics.NewViewTrackingService(viewTrackingRepository, viewAnalyticsRepository, novelChapterRepository, novelRepository, genreRepository, logger, viewTrackingConfig)
	updateStatisticsUseCase := novel_chapter.NewUpdateStatisticsUseCase(chapterService)
	novel_chapterHandler := novel_chapter.NewHandler(chapterService, createChapterUseCase, updateChapterUseCase, deleteChapterUseCase, getChapterUseCase, listChaptersByNovelUseCase, listChaptersByVolumeUseCase, publishChapterUseCase, scheduleChapterUseCase, viewTrackingService, updateStatisticsUseCase)
	userHandler := user.NewHandler(userService)
	listCreatorsUseCase := creator.NewListCreatorsUseCase(creatorService)
	creatorHandler := creator.NewHandler(listCreatorsUseCase, analyticsService)
	organizationService := organization.NewService(organizationRepository)
	organizationHandler := organization.NewHandler(organizationService, analyticsService, logger)
	cacheService := cache.NewCacheService(rdb, logger)
	embeddingHandler := embedding.NewHandler(embeddingService, novelService, cacheService)
	paymentConfigurationRepository := payment.NewPaymentConfigEntRepository(client)
	configUseCase := payment.NewConfigUseCase(paymentConfigurationRepository)
	paymentHandler := payment.NewHandler(configUseCase, logger)
	walletRepository := payment.NewWalletEntRepository(client)
	walletUseCase := payment.NewWalletUseCase(walletRepository, logger)
	coinPackageRepository := payment.NewCoinPackageEntRepository(client)
	topupOrderRepository := payment.NewTopupOrderEntRepository(client, db)
	transactionRepository := payment.NewTransactionEntRepository(client)
	hub := socket.NewHub(logger)
	topupUseCase := payment.NewTopupUseCase(client, walletRepository, coinPackageRepository, topupOrderRepository, transactionRepository, configUseCase, hub, logger)
	transactionUseCase := payment.NewTransactionUseCase(transactionRepository, logger)
	walletHandler := payment.NewWalletHandler(walletUseCase, topupUseCase, transactionUseCase, logger)
	webhookHandler := payment.NewWebhookHandler(topupUseCase, configUseCase, logger)
	socketHandler := socket.NewHandler(hub, logger)
	mediaProgressRepository := media_progress.NewEntRepository(client, db)
	media_progressService := media_progress.NewService(mediaProgressRepository, novelRepository, novelChapterRepository, logger)
	media_progressHandler := media_progress.NewHandler(media_progressService)
	mediaHandler := media.NewHandler(analyticsService)
	handlers := &router.Handlers{
		OAuth2:        handler,
		OAuth2Admin:   adminHandler,
		Auth:          authHandler,
		Genre:         genreHandler,
		Author:        authorHandler,
		Artist:        artistHandler,
		Novel:         novelHandler,
		Volume:        novel_volumeHandler,
		Chapter:       novel_chapterHandler,
		User:          userHandler,
		Creator:       creatorHandler,
		Organization:  organizationHandler,
		Embedding:     embeddingHandler,
		PaymentConfig: paymentHandler,
		Wallet:        walletHandler,
		Webhook:       webhookHandler,
		Socket:        socketHandler,
		MediaProgress: media_progressHandler,
		Media:         mediaHandler,
	}
	services := &router.Services{
		OAuth2:         oAuth2Service,
		OAuth2Admin:    oAuth2AdminService,
		Auth:           authService,
		Email:          service,
		Genre:          genreService,
		Author:         authorService,
		Artist:         artistService,
		Novel:          novelService,
		Volume:         volumeService,
		Chapter:        chapterService,
		ViewTracking:   viewTrackingService,
		Analytics:      analyticsService,
		Creator:        creatorService,
		WebAuthn:       webAuthnService,
		User:           userService,
		Organization:   organizationService,
		Embedding:      embeddingService,
		Cache:          cacheService,
		PaymentConfig:  configUseCase,
		Wallet:         walletUseCase,
		Topup:          topupUseCase,
		TransactionSvc: transactionUseCase,
		MediaProgress:  media_progressService,
		SocketHub:      hub,
	}
	engine := ProvideRouter(cfg, i18nInstance, logger, handlers, services, oAuth2Provider)
	server := ProvideHTTPServer(cfg, engine)
	repositories := &router.Repositories{
		OAuth2Client:       oAuth2ClientRepository,
		OAuth2Session:      oAuth2SessionRepository,
		User:               userRepository,
		Session:            sessionRepository,
		AuthRequest:        authRequestRepository,
		Consent:            consentRepository,
		EmailVerification:  emailVerificationRepository,
		PasswordReset:      passwordResetRepository,
		Genre:              genreRepository,
		Author:             authorRepository,
		Artist:             artistRepository,
		Novel:              novelRepository,
		Volume:             novelVolumeRepository,
		VolumeHistory:      volumeHistoryRepository,
		Chapter:            novelChapterRepository,
		ChapterHistory:     chapterHistoryRepository,
		WebAuthnCredential: webAuthnCredentialRepository,
		WebAuthnSession:    webAuthnSessionRepository,
		ViewAnalytics:      viewAnalyticsRepository,
		ViewTracking:       viewTrackingRepository,
		Role:               roleRepository,
		Creator:            creatorRepository,
		Organization:       organizationRepository,
		PaymentConfig:      paymentConfigurationRepository,
		Wallet:             walletRepository,
		CoinPackage:        coinPackageRepository,
		TopupOrder:         topupOrderRepository,
		Transaction:        transactionRepository,
		MediaProgress:      mediaProgressRepository,
	}
	application := &Application{
		Config:     cfg,
		Logger:     logger,
		Router:     engine,
		HTTPServer: server,
		Redis:      rdb,
		ClickHouse: ch,
		I18n:       i18nInstance,
		Repos:      repositories,
		Services:   services,
		Handlers:   handlers,
		OAuth2:     oAuth2Provider,
		EntClient:  client,
	}
	return application, nil
}

// wire.go:

// ProvideTransactionManager provides the Ent-based transaction manager
func ProvideTransactionManager(client *generated.Client) database.TransactionManager {
	return database.NewTransactionManager(client)
}

// ProvideRedisGoClient exports redis client from wrapper
func ProvideRedisGoClient(rdb *database.RedisClient) *redis.Client {
	return rdb.Client
}

func ProvideEmailConfig(cfg *configs.Config) *configs.EmailConfig {
	return &cfg.Email
}

func ProvideOAuthConfig(cfg *configs.Config) *configs.OAuthConfig {
	return &cfg.OAuth2
}

func ProvideWebAuthnConfig(cfg *configs.Config) configs.WebAuthnConfig {
	return cfg.WebAuthn
}

func ProvideViewTrackingConfig(cfg *configs.Config) *configs.ViewTrackingConfig {
	return &cfg.ViewTracking
}

func ProvideEmbeddingConfig(cfg *configs.Config) *configs.EmbeddingConfig {
	return &cfg.Embedding
}

// ProvideEntClient tạo Ent client từ Config
func ProvideEntClient(ctx context.Context, cfg *configs.Config, logger *zap.Logger) (*generated.Client, error) {
	entClient, err := database.NewEntClient(ctx, &cfg.DB, cfg.Log.DBLogQueries, logger)
	if err != nil {
		return nil, err
	}
	return entClient.Client, nil
}

// ProvideDBFromEnt creates *sql.DB from configs for repos needing raw SQL
func ProvideDBFromEnt(cfg *configs.Config) (*sql.DB, error) {
	dsn := fmt.Sprintf(
		"postgres://%s:%s@%s:%s/%s?sslmode=%s",
		cfg.DB.User,
		cfg.DB.Password,
		cfg.DB.Host,
		cfg.DB.Port,
		cfg.DB.Name,
		cfg.DB.SSLMode,
	)
	return sql.Open("postgres", dsn)
}

var InfraSet = wire.NewSet(
	ProvideRedisGoClient,
	ProvideTransactionManager,
	ProvideEmailConfig,
	ProvideOAuthConfig,
	ProvideWebAuthnConfig,
	ProvideViewTrackingConfig,
	ProvideEmbeddingConfig,
	ProvideEntClient,
	ProvideDBFromEnt,
)

var RepositorySet = wire.NewSet(oauth2.NewOAuth2ClientEntRepository, oauth2.NewOAuth2SessionEntRepository, oauth2.NewConsentEntRepository, oauth2.NewAuthRequestRepository, user.NewUserEntRepository, auth.NewUserRoleEntRepository, user.NewRoleEntRepository, user.NewSessionRepository, auth.NewEmailVerificationEntRepository, auth.NewPasswordResetEntRepository, auth.NewWebAuthnCredentialEntRepository, auth.NewWebAuthnSessionEntRepository, genre.NewEntGenreRepository, author.NewEntAuthorRepository, artist.NewEntArtistRepository, novel.NewEntNovelRepository, novel_volume.NewEntVolumeRepository, novel_volume.NewVolumeHistoryEntRepository, novel_chapter.NewEntChapterRepository, novel_chapter.NewChapterHistoryEntRepository, analytics.NewViewAnalyticsClickHouseRepository, analytics.NewViewTrackingRedisRepository, creator.NewEntRepository, organization.NewEntRepository, payment.NewPaymentConfigEntRepository, payment.NewWalletEntRepository, payment.NewCoinPackageEntRepository, payment.NewTopupOrderEntRepository, payment.NewTransactionEntRepository, media_progress.NewEntRepository, embedding.NewEntRepository)

var OAuth2Set = wire.NewSet(storage.NewSQLStore, storage.NewRedisStore, storage.NewHybridStore, oauth2_2.NewOAuth2Provider)

var ServiceSet = wire.NewSet(user.NewService, oauth2.NewService, oauth2.NewAdminService, auth.NewService, auth.NewWebAuthnService, resend.NewClient, wire.Bind(new(email.EmailSender), new(*resend.Client)), email.NewService, wire.Bind(new(email.EmailService), new(*email.Service)), wire.Bind(new(oauth2.WebAuthnService), new(auth.WebAuthnService)), wire.Bind(new(auth.OAuth2SessionCreator), new(oauth2.OAuth2Service)), genre.NewService, wire.Bind(new(novel.UCGenreService), new(genre.GenreService)), author.NewService, wire.Bind(new(novel.UCAuthorService), new(author.AuthorService)), artist.NewService, wire.Bind(new(novel.UCArtistService), new(artist.ArtistService)), novel.NewService, wire.Bind(new(novel.UCNovelService), new(novel.NovelService)), novel_volume.NewService, novel_chapter.NewService, analytics.NewViewTrackingService, wire.Bind(new(novel_chapter.ViewTracker), new(*analytics.ViewTrackingService)), analytics.NewService, creator.NewService, wire.Bind(new(novel.UCCreatorService), new(creator.CreatorService)), organization.NewService, ProvideNoopEmbedder, embedding.NewService, wire.Bind(new(embedding.ContentFetcher), new(novel.NovelService)), wire.Bind(new(novel.UCEmbeddingService), new(*embedding.Service)), payment.NewConfigUseCase, payment.NewWalletUseCase, payment.NewTransactionUseCase, socket.NewHub, wire.Bind(new(payment.TopupNotifier), new(*socket.Hub)), payment.NewTopupUseCase, media_progress.NewService, cache.NewCacheService, router.NewTopNovelAdapter, wire.Bind(new(novel.TopNovelService), new(*router.TopNovelAdapter)))

// ProvideNoopEmbedder creates a NoopEmbedder that implements Embedder interface
func ProvideNoopEmbedder(cfg *configs.EmbeddingConfig) embedding.Embedder {
	return embedding.NewNoopEmbedder(cfg.Dimensions)
}

var UseCaseSet = wire.NewSet(novel.NewCreateNovelUseCase, novel.NewUpdateNovelUseCase, novel.NewDeleteNovelUseCase, novel.NewGetNovelUseCase, novel.NewListNovelsUseCase, novel.NewIncrementViewCountUseCase, novel.NewGetNovelFullUseCase, genre.NewCreateGenreUseCase, genre.NewUpdateGenreUseCase, genre.NewDeleteGenreUseCase, genre.NewGetGenreUseCase, genre.NewListGenresUseCase, genre.NewListSelectionUseCase, genre.NewMergeGenresUseCase, genre.NewPreviewMergeUseCase, author.NewCreateAuthorUseCase, author.NewUpdateAuthorUseCase, author.NewDeleteAuthorUseCase, author.NewGetAuthorUseCase, author.NewListAuthorsUseCase, author.NewListSelectionUseCase, author.NewMergeAuthorsUseCase, author.NewPreviewMergeUseCase, artist.NewCreateArtistUseCase, artist.NewUpdateArtistUseCase, artist.NewDeleteArtistUseCase, artist.NewGetArtistUseCase, artist.NewListArtistsUseCase, artist.NewListSelectionUseCase, artist.NewMergeArtistsUseCase, artist.NewPreviewMergeUseCase, novel_volume.NewCreateVolumeUseCase, novel_volume.NewUpdateVolumeUseCase, novel_volume.NewDeleteVolumeUseCase, novel_volume.NewGetVolumeUseCase, novel_volume.NewListVolumesByNovelUseCase, novel_volume.NewUpdateDisplayOrderUseCase, novel_volume.NewPublishVolumeUseCase, novel_volume.NewUnpublishVolumeUseCase, novel_chapter.NewCreateChapterUseCase, novel_chapter.NewUpdateChapterUseCase, novel_chapter.NewDeleteChapterUseCase, novel_chapter.NewGetChapterUseCase, novel_chapter.NewListChaptersByNovelUseCase, novel_chapter.NewListChaptersByVolumeUseCase, novel_chapter.NewPublishChapterUseCase, novel_chapter.NewScheduleChapterUseCase, novel_chapter.NewUpdateStatisticsUseCase, auth.NewRegisterUserUseCase, auth.NewVerifyEmailUseCase, auth.NewForgotPasswordUseCase, auth.NewResetPasswordUseCase, creator.NewListCreatorsUseCase)

var HandlerSet = wire.NewSet(oauth2.NewHandler, oauth2.NewAdminHandler, auth.NewHandler, genre.NewHandler, author.NewHandler, artist.NewHandler, novel.NewHandler, novel_volume.NewHandler, novel_chapter.NewHandler, user.NewHandler, creator.NewHandler, organization.NewHandler, embedding.NewHandler, payment.NewHandler, payment.NewWalletHandler, payment.NewWebhookHandler, media_progress.NewHandler, media.NewHandler, socket.NewHandler)

var StructSet = wire.NewSet(wire.Struct(new(router.Repositories), "*"), wire.Struct(new(router.Services), "*"), wire.Struct(new(router.Handlers), "*"))

// Application holds all initialized components
type Application struct {
	Config     *configs.Config
	Logger     *zap.Logger
	Router     *gin.Engine
	HTTPServer *http.Server
	Redis      *database.RedisClient
	ClickHouse *database.ClickHouseClient
	I18n       *i18n.I18n
	Repos      *router.Repositories
	Services   *router.Services
	Handlers   *router.Handlers
	OAuth2     fosite.OAuth2Provider
	EntClient  *generated.Client // Ent ORM client
}

// ProvideHTTPServer creates the HTTP server
func ProvideHTTPServer(cfg *configs.Config, r *gin.Engine) *http.Server {
	return &http.Server{
		Addr:    ":" + cfg.Server.Port,
		Handler: r,
	}
}

// ProvideRouter creates and configures the Gin router
func ProvideRouter(
	cfg *configs.Config,
	i18nInstance *i18n.I18n,
	logger *zap.Logger,
	handlers *router.Handlers,
	services *router.Services,
	oauth2Provider fosite.OAuth2Provider,
) *gin.Engine {
	return router.NewRouterWithHandlers(cfg, i18nInstance, logger, handlers, services, oauth2Provider)
}

// MasterSet contains all providers
var MasterSet = wire.NewSet(
	InfraSet,
	RepositorySet,
	OAuth2Set,
	ServiceSet,
	UseCaseSet,
	HandlerSet,
	StructSet,
	ProvideRouter,
	ProvideHTTPServer, wire.Struct(new(Application), "*"),
)
