// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: token_validation.proto

package tokenvalidation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ValidateTokenRequest contains the token to validate
type ValidateTokenRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Token          string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TokenType      string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`                // "access_token" or "refresh_token", defaults to "access_token"
	RequiredScopes []string               `protobuf:"bytes,3,rep,name=required_scopes,json=requiredScopes,proto3" json:"required_scopes,omitempty"` // Optional scopes that must be present
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_token_validation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_validation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_token_validation_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ValidateTokenRequest) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *ValidateTokenRequest) GetRequiredScopes() []string {
	if x != nil {
		return x.RequiredScopes
	}
	return nil
}

// ValidateTokenResponse contains the validation result
type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                          // Error message if validation failed
	TokenInfo     *TokenInfo             `protobuf:"bytes,3,opt,name=token_info,json=tokenInfo,proto3" json:"token_info,omitempty"` // Token metadata if valid
	UserInfo      *UserInfo              `protobuf:"bytes,4,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`    // User information if available
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_token_validation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_validation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_token_validation_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ValidateTokenResponse) GetTokenInfo() *TokenInfo {
	if x != nil {
		return x.TokenInfo
	}
	return nil
}

func (x *ValidateTokenResponse) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

// TokenInfo contains metadata about the validated token
type TokenInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	TokenType     string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	Scope         []string               `protobuf:"bytes,3,rep,name=scope,proto3" json:"scope,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Audience      []string               `protobuf:"bytes,5,rep,name=audience,proto3" json:"audience,omitempty"`
	Issuer        string                 `protobuf:"bytes,6,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Subject       string                 `protobuf:"bytes,7,opt,name=subject,proto3" json:"subject,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix timestamp
	IssuedAt      int64                  `protobuf:"varint,9,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`    // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenInfo) Reset() {
	*x = TokenInfo{}
	mi := &file_token_validation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenInfo) ProtoMessage() {}

func (x *TokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_token_validation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenInfo.ProtoReflect.Descriptor instead.
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return file_token_validation_proto_rawDescGZIP(), []int{2}
}

func (x *TokenInfo) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *TokenInfo) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenInfo) GetScope() []string {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *TokenInfo) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *TokenInfo) GetAudience() []string {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *TokenInfo) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *TokenInfo) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *TokenInfo) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *TokenInfo) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

// UserInfo contains user information extracted from the token
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	EmailVerified bool                   `protobuf:"varint,5,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,6,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional user claims
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                                                 // Unix timestamp
	TenantId      string                 `protobuf:"bytes,8,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                                     // Current tenant ID for the user (UUID)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_token_validation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_token_validation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_token_validation_proto_rawDescGZIP(), []int{3}
}

func (x *UserInfo) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *UserInfo) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *UserInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *UserInfo) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

var File_token_validation_proto protoreflect.FileDescriptor

const file_token_validation_proto_rawDesc = "" +
	"\n" +
	"\x16token_validation.proto\x12\x0ftokenvalidation\"t\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\x12'\n" +
	"\x0frequired_scopes\x18\x03 \x03(\tR\x0erequiredScopes\"\xb6\x01\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x129\n" +
	"\n" +
	"token_info\x18\x03 \x01(\v2\x1a.tokenvalidation.TokenInfoR\ttokenInfo\x126\n" +
	"\tuser_info\x18\x04 \x01(\v2\x19.tokenvalidation.UserInfoR\buserInfo\"\xff\x01\n" +
	"\tTokenInfo\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\x12\x14\n" +
	"\x05scope\x18\x03 \x03(\tR\x05scope\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12\x1a\n" +
	"\baudience\x18\x05 \x03(\tR\baudience\x12\x16\n" +
	"\x06issuer\x18\x06 \x01(\tR\x06issuer\x12\x18\n" +
	"\asubject\x18\a \x01(\tR\asubject\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\x03R\texpiresAt\x12\x1b\n" +
	"\tissued_at\x18\t \x01(\x03R\bissuedAt\"\xa6\x02\n" +
	"\bUserInfo\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12%\n" +
	"\x0eemail_verified\x18\x05 \x01(\bR\remailVerified\x12:\n" +
	"\x05extra\x18\x06 \x03(\v2$.tokenvalidation.UserInfo.ExtraEntryR\x05extra\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012x\n" +
	"\x16TokenValidationService\x12^\n" +
	"\rValidateToken\x12%.tokenvalidation.ValidateTokenRequest\x1a&.tokenvalidation.ValidateTokenResponseB%Z#wibusystem/pkg/grpc/tokenvalidationb\x06proto3"

var (
	file_token_validation_proto_rawDescOnce sync.Once
	file_token_validation_proto_rawDescData []byte
)

func file_token_validation_proto_rawDescGZIP() []byte {
	file_token_validation_proto_rawDescOnce.Do(func() {
		file_token_validation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_token_validation_proto_rawDesc), len(file_token_validation_proto_rawDesc)))
	})
	return file_token_validation_proto_rawDescData
}

var file_token_validation_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_token_validation_proto_goTypes = []any{
	(*ValidateTokenRequest)(nil),  // 0: tokenvalidation.ValidateTokenRequest
	(*ValidateTokenResponse)(nil), // 1: tokenvalidation.ValidateTokenResponse
	(*TokenInfo)(nil),             // 2: tokenvalidation.TokenInfo
	(*UserInfo)(nil),              // 3: tokenvalidation.UserInfo
	nil,                           // 4: tokenvalidation.UserInfo.ExtraEntry
}
var file_token_validation_proto_depIdxs = []int32{
	2, // 0: tokenvalidation.ValidateTokenResponse.token_info:type_name -> tokenvalidation.TokenInfo
	3, // 1: tokenvalidation.ValidateTokenResponse.user_info:type_name -> tokenvalidation.UserInfo
	4, // 2: tokenvalidation.UserInfo.extra:type_name -> tokenvalidation.UserInfo.ExtraEntry
	0, // 3: tokenvalidation.TokenValidationService.ValidateToken:input_type -> tokenvalidation.ValidateTokenRequest
	1, // 4: tokenvalidation.TokenValidationService.ValidateToken:output_type -> tokenvalidation.ValidateTokenResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_token_validation_proto_init() }
func file_token_validation_proto_init() {
	if File_token_validation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_token_validation_proto_rawDesc), len(file_token_validation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_token_validation_proto_goTypes,
		DependencyIndexes: file_token_validation_proto_depIdxs,
		MessageInfos:      file_token_validation_proto_msgTypes,
	}.Build()
	File_token_validation_proto = out.File
	file_token_validation_proto_goTypes = nil
	file_token_validation_proto_depIdxs = nil
}
